=== dpmland/cli/schemas/dpm.json
{
  "$id": "https://raw.githubusercontent.com/dpmland/dpm/main/schemas/dpm.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "A JSON representation of a Dpm main file.",
  "title": "DPM.json configuration schema!",
  "properties": {
    "name": {
      "description": "The name of the project to use!",
      "type": "string"
    },
    "version": {
      "description": "The version of the project for use with DPM!",
      "type": "string"
    },
    "description": {
      "description": "The description of the project for use with DPM!",
      "type": "string"
    },
    "author": {
      "description": "The author or authors of this project!",
      "type": "string"
    },
    "license": {
      "description": "The license to use in this project!",
      "type": "string"
    },
    "main": {
      "description": "The main file for use in this project!",
      "type": "string"
    },
    "scripts": {
      "description": "The scripts for automate the commands!",
      "type": "object"
    },
    "dependencies": {
      "description": "The dependencies to use in the DPM Project!",
      "type": "object"
    }
  },
  "required": [
    "name",
    "version",
    "description",
    "author",
    "license",
    "main",
    "scripts",
    "dependencies"
  ]
}

=== dpmland/cli/dpm.json
{
  "$schema": "https://dpmland.deno.dev/schema",
  "name": "dpm",
  "version": "0.1.0",
  "description": "A example dpm package",
  "author": "A cool coder human",
  "license": "ISC",
  "main": "mod.ts",
  "scripts": {
    "test": "deno test -A --unstable",
    "fmt": "deno fmt -c deno.json",
    "lint": "deno lint -c deno.json"
  },
  "dependencies": {}
}
